config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#top'

  resources :users,     only: [:show, :index, :edit, :update] do
    get 'edit_detail', to: 'users#edit_detail'
    patch 'update_detail', to: 'users#update_detail'
  end
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    get 'top', to: 'items#top'
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    resources :comments, only: :create
  end
  resources :addresses, only: [:edit, :update]
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
    end
  end  
  resources :categories, only: :show
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  has_many :comments

  # バリデーション
  validates :nickname, :family_name, :first_name, :family_name_kana, :first_name_kana, :year, :month, :day, :number, :gender, :password_confirmation,  presence: true

  # 文字の形式制限
  validates :family_name, :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/,
    message: "全角文字のみが使えます" }
  validates :family_name_kana,:first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/,
    message: "全角カナのみが使えます" }

  # アソシエーション
  has_many :items, dependent: :destroy
  has_one :address
  has_one :card

  mount_uploader :user_image, ImageUploader
  mount_uploader :user_bg_image, ImageUploader
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  #   super
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    unless @user.valid?
      flash.now[:alert] = @user.errors.full_messages
      render :new and return
    end
    session["devise.regist_data"] = {user: @user.attributes}
    session["devise.regist_data"][:user]["password"] = params[:user][:password]
    session["devise.regist_data"][:user]["password_confirmation"] = params[:user][:password_confirmation]
    @address = @user.build_address
    render :new_address
  end


  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    unless @address.valid?
      flash.now[:alert] = @address.errors.full_messages
      render :new_address and return
    end
    @user.build_address(@address.attributes)
    @user.save
    sign_in(:user, @user)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  def address_params
    params.require(:address).permit(:family_name, :first_name, :family_name_kana, :first_name_kana, :postal_code, :city, :local, :block, :building, :number)
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_category
  before_action :set_user_params, only: [:show, :edit, :update]
  before_action :set_user_current, only: [:index, :edit_detail, :update_detail]

  def index
    @items = @user.items
  end

  def show
    @items = @user.items
  end

  def edit
  end

  def update
    @user.update(update_params)
    unless @user.update(update_params)
      redirect_to edit_user_path(@user.id), notice: "変更できません。ニックネームとパスワードは必須項目です"
    end
    sign_in(:user, @user)
  end

  def edit_detail
  end

  def update_detail
    @user.update(update_detail_params)
    unless @user.update(update_detail_params)
      redirect_to user_edit_detail_path(@user.id), notice: "変更できません。メールアドレスとパスワードは必須項目です"
    end
    sign_in(:user, @user)
  end


  private
  
  def set_user_params
    @user = User.find(params[:id])
  end

  def set_user_current
    @user = User.find(current_user.id)
  end

  def update_params
    params.require(:user).permit(:nickname, :introduction, :password, :password_confirmation, :user_image, :user_bg_image)
  end

  def update_detail_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def set_category
    @category_parent_array = []
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent
      end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side-bar.html.haml
.ui__wrapper__side-bar
  .ui__wrapper__side-bar__contents
    %ul
      
      %li
        = link_to user_edit_detail_path(current_user.id)  do
          .ui__wrapper__side-bar__contents__content
            メールアドレス・パスワード変更 >
      %li
        = link_to edit_user_path(current_user.id)  do
          .ui__wrapper__side-bar__contents__content
            プロフィールの変更 >
      %li
        = link_to edit_address_path(current_user.id)  do
          .ui__wrapper__side-bar__contents__content
            配送先情報の変更 >
      %li
        - if @user.card.present?
          = link_to cards_path(current_user.id)  do
            .ui__wrapper__side-bar__contents__content
              お支払い情報の確認、削除 >
        - else
          = link_to new_card_path(current_user.id)  do
            .ui__wrapper__side-bar__contents__content
              お支払い情報の登録 >
      %li
        = link_to users_path(current_user.id) do
          .ui__wrapper__side-bar__contents__content
            出品した商品 >

   

app/views/users/edit.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.ue__wrapper
  = render "side-bar"
  .ue__wrapper__main-bar
    .ue__wrapper__main-bar__contents
      %h2.ue__wrapper__main-bar__contents__title
        プロフィールの変更
      = form_for @user do |f|
        .ue__wrapper__main-bar__contents__content
          .ue__wrapper__main-bar__contents__content__image
            %label(for="user_user_image")
              .ue__wrapper__main-bar__contents__content__image__user
                %img#avatar_img_prev.hidden
                - if @user.user_image.present?
                  = image_tag @user.user_image.url, class: "avatar_present_img"
                - else
                  =image_tag "member_photo_noimage_thumb.png", class: "avatar_present_img"
                = f.file_field :user_image
                
                
                
                
        
        .ue__wrapper__main-bar__contents__content
          = f.label "ニックネーム", class: "content-title"
          %br/
          = f.text_field :nickname, autofocus: true, autocomplete: "nickname", placeholder: "ニックネーム"
        .ue__wrapper__main-bar__contents__content
          = f.label "自己紹介", class: "content-title"
          %br/
          = f.text_area :introduction, autofocus: true, autocomplete: "introduction", placeholder: "例)こんにちは。着古した子供服をたくさん出品しています。女の子、sizeは100が多いです。よろしくお願いいたします。"
        .ue__wrapper__main-bar__contents__content
          = f.label "パスワード", class: "content-title"
          - if @minimum_password_length
            %em
            (7 characters minimum)
          %br/
          = f.password_field :password, autocomplete: "new-password", placeholder: "半角英数字７字以上"
        .ue__wrapper__main-bar__contents__content
          = f.label "パスワード（確認用）", class: "content-title"
          - if @minimum_password_length
            %em
              (7 characters minimum)
          %br/
          = f.password_field :password_confirmation, autocomplete: "password_confirmation", placeholder: "半角英数字７字以上"
        .ue__wrapper__main-bar__contents__content
          = f.submit "更新する", class: "update-btn"
          = link_to "もどる", users_path(current_user), class: "back-btn"
= render partial: 'layouts/footer', locals: { footer: @footer }
- if user_signed_in?
  %a(href="/items/new")
    .sellBtn
      %span.sellBtn__text 出品する
      = image_tag 'icon_camera.png', alt: '', height: '', width: '', class: 'sellBtn__icon'
- else
  %a(href="/users/sign_in")
    .sellBtn
      %span.sellBtn__text ログインして出品する
      = image_tag 'icon_camera.png', alt: '', height: '', width: '', class: 'sellBtn__icon'

app/views/users/edit_detail.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.ue__wrapper
  = render "side-bar"
  .ue__wrapper__main-bar
    .ue__wrapper__main-bar__contents
      %h2.ue__wrapper__main-bar__contents__title
        メールアドレス・パスワード変更
      = form_for(@user, url: {controller: 'users', action: 'update_detail' }) do |f|
        .ue__wrapper__main-bar__contents__content
          = f.label "e-mail", class: "content-title"
          %br/
          = f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "e-mail"
        .ue__wrapper__main-bar__contents__content
          = f.label "パスワード", class: "content-title"
          - if @minimum_password_length
            %em
            (7 characters minimum)
          %br/
          = f.password_field :password, autocomplete: "new-password", placeholder: "半角英数字７字以上"
        .ue__wrapper__main-bar__contents__content
          = f.label "パスワード（確認用）", class: "content-title"
          - if @minimum_password_length
            %em
              (7 characters minimum)
          %br/
          = f.password_field :password_confirmation, autocomplete: "password_confirmation", placeholder: "半角英数字７字以上"
        .ue__wrapper__main-bar__contents__content
          = f.submit "更新する", class: "update-btn"
          = link_to "もどる", users_path(current_user), class: "back-btn"
= render partial: 'layouts/footer', locals: { footer: @footer }
- if user_signed_in?
  %a(href="/items/new")
    .sellBtn
      %span.sellBtn__text 出品する
      = image_tag 'icon_camera.png', alt: '', height: '', width: '', class: 'sellBtn__icon'
- else
  %a(href="/users/sign_in")
    .sellBtn
      %span.sellBtn__text ログインして出品する
      = image_tag 'icon_camera.png', alt: '', height: '', width: '', class: 'sellBtn__icon'

app/views/users/index.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.ui__wrapper
  = render "side-bar"
  .ui__wrapper__main-bar
    .ui__wrapper__main-bar__contents
      %h2.ui__wrapper__main-bar__contents__title 
        #{@user.nickname}さんが出品した商品
      .ui__wrapper__main-bar__contents-flex
        - @items.each do |item|
          = link_to item_path(item.id),class: "ui__wrapper__main-bar__contents__content__link" do
            .e__middle__container__border
              .e__middle__container__border__content
                .e__middle__container__border__content__image
                  = image_tag item.images[0].src.url
                  -if item.buyer_id.present?
                    .e__middle__container__border__content__image--triangle
                    .e__middle__container__border__content__image__soldout
                      SOLD
                .e__middle__container__border__content__info
                  .e__middle__container__border__content__info__name
                    = item.name
                  .e__middle__container__border__content__info__price
                    ¥
                    = item.price
                    =icon('far','heart') do
                      %span 100
      
= render partial: 'layouts/footer', locals: { footer: @footer }
- if user_signed_in?
  %a(href="/items/new")
    .sellBtn
      %span.sellBtn__text 出品する
      = image_tag 'icon_camera.png', alt: '', height: '', width: '', class: 'sellBtn__icon'
- else
  %a(href="/users/sign_in")
    .sellBtn
      %span.sellBtn__text ログインして出品する
      = image_tag 'icon_camera.png', alt: '', height: '', width: '', class: 'sellBtn__icon'

app/views/users/show.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.u_body
  .u_container
    .u_profile 
      .u_profile_box
        - if user_signed_in? && current_user.id == @user.id
          = link_to users_path(current_user), class: "u_profile_box_btn" do
            - if @user.user_image?
              = image_tag @user.user_image.url, class: "user_image"
            - else
              =image_tag "member_photo_noimage_thumb.png",size: "180x180" 
            %h2.u_profile_box_btn_name #{@user.nickname}
          .u_profile_box_grade
            %span.u_profile_box_grade-number 評価数 120
            %span.u_profile_box_grade-amount 出品数 100
        - else
          = link_to "", class: "u_profile_box_btn" do
            - if @user.user_image?
              = image_tag @user.user_image.url, class: "user_image"
            - else
              =image_tag "member_photo_noimage_thumb.png",size: "200x180" 
            %h2.u_profile_box_btn_name #{@user.nickname}
          .u_profile_box_grade
            %span.u_profile_box_grade-number 評価数 120
            %span.u_profile_box_grade-amount 出品数 100
    .u_detail
      .u_detail_review-box
        .u_detail_review-box_each
          %i.fas.fa-laugh.u_detail_review-box_each_good_icon
          .u_detail_review-box_each_good_number 100
        .u_detail_review-box_each
          %i.fas.fa-meh.u_detail_review-box_each_normal_icon
          .u_detail_review-box_each_normal_number 20
        .u_detail_review-box_each
          %i.fas.fa-frown.u_detail_review-box_each_bad_icon
          .u_detail_review-box_each_bad_number 0
      .u_detail_content
        %p.u_detail_content_comment
          = simple_format @user.introduction
    .u_sns
      %ul.u_sns-box
        %li.u_sns-box_facebook
          = link_to "#", class:"u_sns-box_facebook_link" do
            %i.fab.fa-facebook-square.u_sns-box_facebook_link_icon
        %li.u_sns-box_twitter
          = link_to "#", class:"u_sns-box_twitter_link" do
            %i.fab.fa-twitter-square.u_sns-box_twitter_link_icon
          %li.u_sns-box_line
            = link_to "#", class:"u_sns-box_line_link" do
              %i.fab.fa-line.u_sns-box_line_link_icon
    .u_item-box
      %h2.u_item-box_user-name この出品者の商品
      .u_item-box_container
        - @items.each do |item|
          .u_item-box_container_item
            = link_to item_path(item.id),class:".u_item-box_container_item_link" do
              .u_item-box_container_item_link-box
                = image_tag item.images[0].src.url, class: "first-Image"
                -if item.buyer_id.present?
                  .d-itemBox__body--triangle
                  .d-itemBox__body__soldout
                    SOLD
              .u_item-box_container_item_link_body
                %h3.u_item-box_container_item_link_body-name
                  = item.name
                .u_item-box_container_item_link_body_under
                  .u_item-box_container_item_link_body_under-price
                    = item.price
                  .u_item-box_container_item_link_body_under-favorite
                    %i.far.fa-heart.u_item-box_container_item_link_body_under-favorite_icon
                    %span.u_item-box_container_item_link_body_under-favorite_number 12
= render partial: 'layouts/footer', locals: { footer: @footer }

app/views/users/update.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.after-sign-up
  .after-sign-up_content
    .after-sign-up_content_box
      %h1.after-sign-up_content_box_message 変更が完了しました
      .after-sign-up_content_box_image
      %p.after-sign-up_content_box_p 引き続きお買い物をお楽しみください
= render partial: 'layouts/footer', locals: { footer: @footer }

app/views/users/update_detail.html.haml
.t__main
  .t__head__bar
    .t__head__bar__box
      .t__head__bar__box-logo
        %a(href="/")
          = image_tag 'logo.png', alt: '', height: '40px', width: '140px', class: 'img-logo'
      %input.t__head__bar__box-text-box{:name => "search", :placeholder => "キーワードから探す", :type => "search", :value => ""}/
      .t__head__bar__box-text-box-btn(type="submit")
        %a(href="/")
          = image_tag 'icon-search 1.png', alt: '',height: '22px',width:'22px',type: 'submit', class: 't__head__bar__box-text-box-btn-icon'
    .t__head__bar__search
      .t__head__bar__search__box
        %a(id="categoryBtn" href="/")
          .t__head__bar__search__box-categoryカテゴリー
        %a(id="brandBtn" href="/")
          .t__head__bar__search__box-brandブランド
      .t__head__bar__search__select
        = link_to new_user_session_path,id: "logBtn" do
          .t__head__bar__search__select-login ログイン
        = link_to new_user_registration_path,id: "newBtn" do
          .t__head__bar__search__select-login 新規会員登録
.after-sign-up
  .after-sign-up_content
    .after-sign-up_content_box
      %h1.after-sign-up_content_box_message 変更が完了しました
      .after-sign-up_content_box_image
      %p.after-sign-up_content_box_p お手数ですが、もう一度ログインをお願いします。
= render partial: 'layouts/footer', locals: { footer: @footer }