config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#top'

  resources :users,     only: [:show, :index, :edit, :update] do
    get 'edit_detail', to: 'users#edit_detail'
    patch 'update_detail', to: 'users#update_detail'
  end
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    get 'top', to: 'items#top'
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    resources :comments, only: :create
  end
  resources :addresses, only: [:edit, :update]
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
    end
  end  
  resources :categories, only: :show
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  validates :user_id, :name, :description, :price, :condition_id, :wait, :postage, :category_id, :brand_id, :prefecture_id, presence: true
  validates :images, presence: true
  validates :price, :numericality => { :greater_than => 299 }
  validates :price, :numericality => { :less_than => 9999999  }
  belongs_to :user, optional: true
  has_many :comments
  belongs_to :brand
  belongs_to :category
  
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :condition
  belongs_to_active_hash :brand

  def previous
    Item.where("id < ?", self.id).order("id DESC").first
  end

  def next
    Item.where("id > ?", self.id).order("id ASC").first
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:update, :edit, :destroy]
  before_action :move_to_root, except: [:index, :show, :top]
  before_action :correct_user, only: [:edit, :update]
  def index
    @items = Item.includes(:images).order('created_at DESC').page(params[:page]).per(5)
  end
  
  def new
    @item = Item.new
    @item.images.new
    
    def get_category_children
      @category_children = Category.find_by(id: "#{params[:parent_id]}", ancestry: nil).children
    end
  
    def get_category_grandchildren
      @category_grandchildren = Category.find("#{params[:child_id]}").children
    end
  end
  
  def create
    
    @item = Item.create(item_params)
    if @item.save
      redirect_to items_path, notice: "出品しました"
    else
      redirect_to new_item_path, notice: "出品できません。入力必須項目を確認してください"
    end
  end

  

  def edit
  end  

  def update
    if @item.update(item_params)
      redirect_to item_path(@item.id), notice: "商品情報を編集しました"
    else
      redirect_to edit_item_path, notice: "編集できません。入力必須項目を確認してください"
    end
  end

  def destroy
    if @item.destroy
      redirect_to items_path, notice: "商品を削除しました"
    else
      redirect_to item_path, notice: "商品を削除できませんでした"
    end
  end
  
  def show
    @item = Item.includes(:images)
    @item = Item.find(params[:id])
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def top
    @items = Item.includes(:images).order('created_at DESC').limit(3)
    @category = Item.where(category_id: [1...200]).includes(:images).order('created_at DESC').limit(3)
    
  end
  
  private
  def item_params
    params.require(:item).permit(:name, :description, :size, :brand_id, :price, :condition_id, :wait, :postage, :category_id, :prefecture_id, :buyer_id, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)  
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_root
    redirect_to root_path unless user_signed_in?
  end
  def correct_user
    if @current_user.id !=  @item.user_id
     redirect_to root_path
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_category.html.haml
= link_to item_path(item.id) do
  .e__middle__container__border
    .e__middle__container__border__content
      .e__middle__container__border__content__image
        = image_tag item.images[0].src.url
        -if item.buyer_id.present?
          .e__middle__container__border__content__image--triangle
          .e__middle__container__border__content__image__soldout
            SOLD
      .e__middle__container__border__content__info
        .e__middle__container__border__content__info__name
          = item.name
        .e__middle__container__border__content__info__price
          ¥
          = item.price
          =icon('far','heart') do
            %span 100

app/views/items/_form.html.haml
.n__container
  .n__logo
    = link_to image_tag('logo.png', :width => '170', :height => '60'), root_path
      
  .n__form__container
    =form_for @item do |f|
      %ul
        .n__image__container
          %p.message 商品出品画像（必須）
          %p.message 最大5枚までアップロード出来ます
          .post__drop__box__container
            .prev-content
            .label-content
              %label{for: "item_images_attributes_0_src", class: "label-box", id: "label-box--0"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              = f.fields_for :images do |i|
                = i.file_field :src, class: "hidden-field"
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][1][src]", id: "item_images_attributes_1_src" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][2][src]", id: "item_images_attributes_2_src" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][3][src]", id: "item_images_attributes_3_src" }
                %input{class:"hidden-field", type: "file", name: "item[images_attributes][4][src]", id: "item_images_attributes_4_src" }
        .n__item__container
          %p.message 商品名（必須）
          = f.text_field :name, class: "name-box",  placeholder: "商品名（必須 40文字まで)"
          %p.message 商品の説明（必須）
          = f.text_area :description, class: "description-box", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）おじいちゃんの形見です。", rows: "5"
        .n__details__container
          %p.message 商品の詳細
          %p.message サイズ（任意)
          = f.text_field :size, class: "select-box",  placeholder: "（例）S, M, L"
          %p.message カテゴリー（必須)
          .sell-category-box
            = f.collection_select :category_id, @category_parent_array, :id, :name, {prompt: "---"}, {class: 'sell__item-category', id: 'parent_category'}
          %p.message ブランド（必須）
          = f.collection_select :brand_id, Brand.all, :id, :name, {}, {class: "select-box"}
          %p.message 商品の状態（必須）
          = f.collection_select :condition_id, Condition.all, :id, :name, {}, {class: "select-box"}
        .n__post__container
          %p.message 配送について
          %p.message 配送量の負担（必須）
          =f.select :postage,[["送料込み(出品者負担)"]], {prompt: "---"}, {class: "select-box"}
          %p.message 発送元の地域（必須）
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {}, {class: "select-box"}
          %p.message 発送までの日数（必須）
          =f.select :wait,[["1~2日で発送"], ["2~3日で発送"],["4~7日で発送"]], {prompt: "---"},{class:"select-box"}
        .n__price__container
          %p.message 価格（¥300〜9,999,999）
          .content-flex
            .message 販売価格（必須）
            .price
              %span ¥
              =f.number_field :price, placeholder: "0", type: "number", class:"price-box"
      .n__submit__container
        .button
          =f.submit "出品する", class: "exhibition"
        .back
          = link_to "もどる", root_path
      .n__attention__container
        %p.message 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  .n__end__logo__container
    .n__end__logo__container__end__logo
      = link_to image_tag('logo.png', :width => '170', :height => '60'), root_path
      %p ©️Frema.inc 

app/views/items/_item.html.haml
= link_to item_path(item.id) do
  .e__middle__container__border
    .e__middle__container__border__content
      .e__middle__container__border__content__image
        = image_tag item.images[0].src.url
        -if item.buyer_id.present?
          .e__middle__container__border__content__image--triangle
          .e__middle__container__border__content__image__soldout
            SOLD
      .e__middle__container__border__content__info
        .e__middle__container__border__content__info__name
          = item.name
        .e__middle__container__border__content__info__price
          ¥
          = item.price
          =icon('far','heart') do
            %span 100

app/views/items/edit.html.haml
.n__container
  .n__logo
    = link_to image_tag('logo.png', :width => '170', :height => '60'), root_path
      
  .n__form__container
    =form_for @item do |f|
      %ul
        .n__image__container
          %p.message 商品出品画像（必須）
          %p.message 最大5枚までアップロード出来ます
          .post__drop__box__container
            .prev-content
              - @item.images.each do |image|
                .preview-box
                  .upper-box
                    = image_tag image.src.url, width: "112", height: "112", alt: "preview"
                  .lower-box
                    .delete-box
                      .delete-btn
                        %span 削除
            .label-content
              %label{for: "item_images_attributes_#{@item.images.length}_src", class: "label-box", id: "label-box--#{@item.images.length}"}
                %pre.label-box__text-visible クリックしてファイルをアップロード
            .hidden-content
              =f.fields_for :images do |i|
                = i.file_field :src, class: "hidden-field"
                = i.check_box :_destroy, class: "hidden-checkbox"
              - @item.images.length.upto(4) do |i|
                %input{name: "item[images_attributes][#{i}][src]", id: "item_images_attributes_#{i}_src", class: "hidden-field", type: "file"}
        .n__item__container
          %p.message 商品名（必須）
          = f.text_field :name, class: "name-box",  placeholder: "商品名（必須 40文字まで)"
          %p.message 商品の説明（必須）
          = f.text_area :description, class: "description-box", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）おじいちゃんの形見です。", rows: "5"
        .n__details__container
          %p.message 商品の詳細
          %p.message サイズ（任意)
          = f.text_field :size, class: "select-box",  placeholder: "（例）S, M, L"
          %p.message カテゴリー（必須)
          .sell-category-box
            = f.collection_select :category_id, @category_parent_array, :id, :name, {prompt: "---"}, {class: 'sell__item-category', id: 'parent_category'}
          %p.message ブランド（必須）
          = f.collection_select :brand_id, Brand.all, :id, :name, {}, {class: "select-box"}
          %p.message 商品の状態（必須）
          = f.collection_select :condition_id, Condition.all, :id, :name, {}, {class: "select-box"}
        .n__post__container
          %p.message 配送について
          %p.message 配送量の負担（必須）
          =f.select :postage,[["送料込み(出品者負担)"]], {prompt: "---"}, {class: "select-box"}
          %p.message 発送元の地域（必須）
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {}, {class: "select-box"}
          %p.message 発送までの日数（必須）
          =f.select :wait,[["1~2日で発送"], ["2~3日で発送"],["4~7日で発送"]], {prompt: "---"},{class:"select-box"}
        .n__price__container
          %p.message 価格（¥300〜9,999,999）
          .content-flex
            .message 販売価格（必須）
            .price
              %span ¥
              =f.number_field :price, placeholder: "0", type: "number", class:"price-box"
      .n__submit__container
        .button
          =f.submit "商品情報を編集する", class: "exhibition"
        .back
          = link_to "編集しないで戻る", item_path(@item.id)
      .n__attention__container
        %p.message 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  .n__end__logo__container
    .n__end__logo__container__end__logo
      = link_to image_tag('logo.png', :width => '170', :height => '60'), root_path
      %p ©️Frima.inc 

app/views/items/index.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.e__center
  .e__center__image
    .e__center__image__content
      %h2(class=".t__center__image__content-text")スマホで簡単！フリマアプリ
      %h2.e__center__image__content-message
        %p.e__center__image__content-message-line
          FURIMAはだれでも簡単に出品・購入できる
          %br
          フリマアプリです
      .e__center__image__content-icon
        .e__center__image__content-icon-app
        .e__center__image__content-icon-google
          
            
.e__middle
  .e__middle__title
    %h1 新着アイテム一覧
  .e__middle__container
    = render @items
  .e__middle__page
    = paginate(@items)
= render partial: 'layouts/footer', locals: { footer: @footer }
%a(href="/items/new")
  .sellBtn
    %span.sellBtn__text 出品する
    = image_tag 'icon_camera.png', alt: '', height: '', width: '', class: 'sellBtn__icon'
          
        
      

app/views/items/new.html.haml
= render partial: 'form'

app/views/items/show.html.haml
.d-header
  = render partial: 'layouts/header', locals: { header: @header }

.d-main
  .d-showMain
    .d-content
      .d-itemBox
        .d-itemBox__name
          =@item.name
        .d-itemBox__body          
          %ul
            %li
              = image_tag @item.images[0].src.url, class:"firstImage"
              -if @item.buyer_id.present?
                .d-itemBox__body--triangle
                .d-itemBox__body__soldout
                  SOLD
              %ul
                - @item.images.each do |image|
                  %li
                    = image_tag image.src.url, :width => "75", :height => "75",class:"imageList"
        .d-itemBox__price
          ¥
          =@item.price
          .d-itemBox__price-detail
            %span (税込)
            %span 送料込み
        .d-itemDetail
          .noticeMsg
            %p
              = simple_format @item.description
        .d-table
          %table
            %tbody
              %tr
                %th 出品者
                %td.d-table--blue
                  
                  = link_to @item.user.nickname, "/users/#{@item.user_id}"
                  
                 
              %tr
                %th カテゴリー
                %td.d-table--blue
                  = link_to category_path(@item.category.id) do
                    =@item.category.name
              %tr
                %th ブランド
                %td 
                  =@item.brand.name
              %tr
                %th 商品のサイズ
                %td 
                  =@item.size
              %tr
                %th 商品の状態
                %td
                  =@item.condition.name
              %tr
                %th 配送料の負担
                %td 
                  =@item.postage
              %tr
                %th 発送元の地域
                %td
                  = @item.prefecture.name
              %tr
                %th 発送日の目安
                %td 
                  =@item.wait
        .d-optonalArea
          %ul
            %li.d-optinalBtn.d-likeBtn
              =icon('fa','star')
              お気に入り 0
          %ul.d-optional
            %li.d-optionalBtn
              =link_to item_path(@item), method: :get, data: { confirm: '不適切な商品を報告しますか？' } do
                =icon('fa','flag')
                不適切な商品の通報
      .d-itemChangeBox
        %ul.d-itemChangeBox__btnList
          -if @item.buyer_id.present?
            %li.d-itemChangeBox__btnList__soldOutNotice
              売り切れました
          -elsif user_signed_in? && current_user.id == @item.user_id
            %li
              = button_to "商品の編集", edit_item_path(@item), id: "d-edit", method: :get
            or
            %li
              = button_to "この商品を削除する", item_path(@item), method: :delete, data: {confirm: "削除しますか？"}
          -elsif user_signed_in? == false
            = link_to new_user_session_path do
              %button.d-itemChangeBox__btnList__buyBtn
                ログインして購入する
          -else
            %li
              = link_to item_purchase_index_path(@item.id) do
                %button.d-itemChangeBox__btnList__buyBtn
                  購入画面に進む
      .d-commentBox
        - if @comments
          - @comments.each do |comment|
            .d-commentBox__list
              .d-commentBox__list__icon
                =icon('fa','user')
              .d-commentBox__list__content
                .d-commentBox__list__content__name
                  = link_to comment.user.nickname, "/users/#{comment.user_id}"
                .d-commentBox__list__content__message
                  = comment.text
                .d-commentBox__list__content__date
                  = comment.updated_at

        -if @item.buyer_id.present? && user_signed_in?
          =form_for [@item, @comment] do |f|
            = f.text_area :text, disabled: true
            .d-noticeMsg
              %p
                相手のことを考え丁寧なコメントを心がけましょう。
                %br 不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br
            = f.submit "売り切れのためコメントできません", class: "d-commentBtn", disabled: true
        -elsif user_signed_in?
          =form_for [@item, @comment] do |f|
            = f.text_area :text
            .d-noticeMsg
              %p
                相手のことを考え丁寧なコメントを心がけましょう。
                %br 不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br
            = f.submit "コメントする", class: "d-commentBtn"
        -else
    .d-links
      %ur
        %li 
          - if @item.next.present?
            = link_to item_path(@item.next) do
              <
              = @item.next.name
        %li 
          - if @item.previous.present?
            = link_to item_path(@item.previous) do
              = @item.previous.name
              >

.d-footer
  = render partial: 'layouts/footer', locals: { footer: @footer }

app/views/items/top.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.t__center
  .t__center__image
    .t__center__image__content
      %h2(class=".t__center__image__content-text")人生を変えるフリマアプリ
      %h2.t__center__image__content-message
        %p.t__center__image__content-message-line
          FURIMAはだれでも簡単に出品・購入できる
          %br
          フリマアプリです
      .t__center__image__content-icon
        .t__center__image__content-icon-app
          =link_to "http://google.co.jp", id: 'aBtn' do
            = image_tag 'apple-icon.png', alt: '', class: 'apple'
        .t__center__image__content-icon-google
          =link_to "http://google.co.jp", id: 'gBtn' do
            = image_tag 'google-play.png', alt: '', class: 'google'

.t__center__middle
  .t__center__middle__title
    %h2.t__center__middle__title-text FURIMAが選ばれる3つの理由
  .t__center__middle__content
    .t__center__middle__content__box
      .t__center__middle__content__box__image
        = image_tag 'pict-reason-01.jpg', alt: '' , width: '100%', class: ''
        .t__center__middle__content__box__image__num 1
      .t__center__middle__content__box__message
        .t__center__middle__content__box__message--left 3分
        .t__center__middle__content__box__message--right ですぐに出品
      .t__center__middle__content__box__message--bottom スマホで入力するだけで簡単に出品できる！
    .t__center__middle__content__box
      .t__center__middle__content__box__image
        = image_tag 'pict-reason-02.jpg', alt: '', height: '', width: '100%', class: ''
        .t__center__middle__content__box__image__num 2
      .t__center__middle__content__box__message
        .t__center__middle__content__box__message--left シンプル
        .t__center__middle__content__box__message--right で使いやすい
      .t__center__middle__content__box__message--bottom めんどくさい入力は必要なく、検索も購入もスムーズ！
    .t__center__middle__content__box--last
      .t__center__middle__content__box--last__image
        = image_tag 'pict-reason-03.jpg', alt: '', height: '', width: '100%', class: ''
        .t__center__middle__content__box--last__image__num 3
      .t__center__middle__content__box--last__message
        .t__center__middle__content__box--last__message--left 手数料
        .t__center__middle__content__box--last__message--right 業界最安
      .t__center__middle__content__box--last__message--bottom 最大3%でお得に出品&購入！
.t__center__middle__image
  .t__center__middle__image__sentence
    %h2.t__center__middle__image__sentence__title 会員数日本一位 
    .t__center__middle__image__sentence__box
      %p.t__center__middle__image__sentence__box__text
        FURIMAは、フリマアプリで最も人気。
        %br 出品・購入回数も業界最多です！
        ほしかったあの商品に出会えるかもしれません。
  .t__center__middle__image-icon
    .t__center__middle-icon-app
      =link_to "http://google.co.jp", id: 'aBtn' do
        = image_tag 'apple-icon.png', alt: '', class: 'apple'
    .t__center__middle-icon-google
      =link_to "http://google.co.jp", id: 'gBtn' do
        = image_tag 'google-play.png', alt: '', class: 'google'
.t__center__bottom
  .t__center__bottom__title 
    %p FURIMAの特徴
    %after
  .t__center__bottom__image
    .t__center__bottom__image__icon
      .t__center__bottom__image__icon--1
        = image_tag 'icon-01.png', alt: '', height: '', width: '100%', class: 'img1'
      .t__center__bottom__image__sentence
        %h3 簡単に売り買いできる
        %p スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
    .t__center__bottom__image__icon
      .t__center__bottom__image__icon--2
        = image_tag 'icon-03.png', alt: '', height: '', width: '100%', class: 'img2'
      .t__center__bottom__image__sentence
        %h3 売上金は即日振込みに対応
        %p 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
    .t__center__bottom__image__icon
      .t__center__bottom__image__icon--3
        = image_tag 'icon-04.png', alt: '', height: '', width: '100%', class: 'img3'
      .t__center__bottom__image__sentence
        %h3 様々な支払いに対応
        %p お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
.t__pickup
  .t__pickup__category
    %h2 ピックアップカテゴリー
    %h3 新規投稿商品
  .t__pickup__index
    .t__pickup__index__new
      =render @items
    .t__pickup__index__more
      = link_to 'もっと見る>',items_path
.t__pickup
  .t__pickup__category
    %h2 ピックアップカテゴリー
    %h3 レディース
  .t__pickup__index
    .t__pickup__index__new
      -@category.each do |category|
        = render partial: "items/category", locals:{item: category}
    .t__pickup__index__more

   

.t__bottom
  .t__bottom__innner
    %h2.t__bottom__innner__title だれでもかんたん、人生を変えるフリマアプリ
    %p.t__bottom__innner__text 今すぐ無料ダウンロード！
    .t__bottom__innner__icon
      .t__bottom__innner__icon-app
        =link_to "http://google.co.jp", id: 'aBtn' do
          = image_tag 'apple-icon.png', alt: '', class: 'apple'
      .t__bottom__innner__icon-google
        =link_to "http://google.co.jp", id: 'gBtn' do
          = image_tag 'google-play.png', alt: '', class: 'google'
= render partial: 'layouts/footer', locals: { footer: @footer }
- if user_signed_in?
  %a(href="/items/new")
    .sellBtn
      %span.sellBtn__text 出品する
      = image_tag 'icon_camera.png', alt: '', height: '', width: '', class: 'sellBtn__icon'
- else
  %a(href="/users/sign_in")
    .sellBtn
      %span.sellBtn__text ログインして出品する
      = image_tag 'icon_camera.png', alt: '', height: '', width: '', class: 'sellBtn__icon'