config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root 'items#top'

  resources :users,     only: [:show, :index, :edit, :update] do
    get 'edit_detail', to: 'users#edit_detail'
    patch 'update_detail', to: 'users#update_detail'
  end
  resources :items do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    get 'top', to: 'items#top'
    resources :purchase, only: [:index] do
      collection do
        post 'pay', to: 'purchase#pay'
        get 'done', to: 'purchase#done'
      end
    end
    resources :comments, only: :create
  end
  resources :addresses, only: [:edit, :update]
  resources :cards, only: [:new, :show, :destroy] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
    end
  end  
  resources :categories, only: :show
end

app/models/card.rb
class Card < ApplicationRecord

  belongs_to :user
  
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card, only: [:destroy, :show]
  before_action :set_category
  def new
    card = Card.where(user_id: current_user.id)
    redirect_to action: "show" if card.exists?
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = Rails.application.secrets.payjp_private_key
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      unless @card.save
        redirect_to action: "pay"
      end
    end
  end

  def destroy #PayjpとCardデータベースを削除します
    unless @card.blank?
      Payjp.api_key = Rails.application.secrets.payjp_private_key
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    if @card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = Rails.application.secrets.payjp_private_key
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private
  def set_card
    @card = Card.where(user_id: current_user.id).first
  end

  def set_category
    @category_parent_array = []
      Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent
      end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/destroy.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.after-sign-up
  .after-sign-up_content
    .after-sign-up_content_box
      %h1.after-sign-up_content_box_message お支払い情報の削除が完了しました
      .after-sign-up_content_box_image
      %p.after-sign-up_content_box_p 引き続きお買い物をお楽しみください
= render partial: 'layouts/footer', locals: { footer: @footer }

app/views/cards/new.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.p-wrapper
  .p-sign_up_main
    .p-sign_up_main_content お支払い方法
  .p-card_input
    = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm", class: "p-card_input_form") do
      .p-card_input_form_container
        .p-card_input_form_container_group
          %label.p-card_input_form_container_group_label 
            カード番号
            %span.p-card_input_form_container_group_label_span 必須
          = text_field_tag "number", "", class: "p-card_input_form_container_group_input", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
          %ul.p-card_input_form_container_group_ul
            %li.p-card_input_form_container_group_ul_li
              %img{:alt => "visa", :height => "20", :src => "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2482339763", :width => "49"}
            %li.p-card_input_form_container_group_ul_li
              %img{:alt => "master-card", :height => "20", :src => "//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2482339763", :width => "34"}
            %li.p-card_input_form_container_group_ul_li
              %img{:alt => "saison-card", :height => "20", :src => "//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2482339763", :width => "30"}
            %li.p-card_input_form_container_group_ul_li
              %img{:alt => "jcb", :height => "20", :src => "//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2482339763", :width => "32"}
            %li.p-card_input_form_container_group_ul_li
              %img{:alt => "american_express", :height => "20", :src => "//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2482339763", :width => "21"}
            %li.p-card_input_form_container_group_ul_li
              %img{:alt => "dinersclub", :height => "20", :src => "//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2482339763", :width => "32"}
            %li.p-card_input_form_container_group_ul_li
              %img{:alt => "discover", :height => "20", :src => "//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2482339763", :width => "32"}
        .p-card_input_form_container_group
          %label.p-card_input_form_container_group_label 
            有効期限
            %span.p-card_input_form_container_group_label_span 必須
          .p-card_input_form_container_group_wrap
            .p-card_input_form_container_group_wrap_half
              %select.p-card_input_form_container_group_wrap_half_month#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span 月
            .p-card_input_form_container_group_wrap_half
              %select.p-card_input_form_container_group_wrap_half_year#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %span 年
        .p-card_input_form_container_group
          %label.p-card_input_form_container_group_label
            セキュリティーコード
            %span.p-card_input_form_container_group_label_span 必須
          = text_field_tag "cvc", "", class: "p-card_input_form_container_group_input", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
          #card_token
        = submit_tag "追加する", class: "p-card_input_form_container_submit", id: "token_submit"
        = link_to "戻る", :back, class: "p-card_input_form_container_back"
= render partial: 'layouts/footer', locals: { footer: @footer }

app/views/cards/pay.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.after-sign-up
  .after-sign-up_content
    .after-sign-up_content_box
      %h1.after-sign-up_content_box_message お支払い情報の登録が完了しました
      .after-sign-up_content_box_image
      %p.after-sign-up_content_box_p 引き続きお買い物をお楽しみください
= render partial: 'layouts/footer', locals: { footer: @footer }

app/views/cards/show.html.haml
= render partial: 'layouts/header', locals: { header: @header }
.p-wrapper
  .c-body
    .c-body_container
      %h2.c-body_container_message お支払い方法
      .c-body_container_inner
        .c-body_container_inner_body 
          クレジットカード情報
          .c-body_container_inner_body_content
            %img{:alt => "visa-logo", :src => "//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?3296506464", :width => "49"}
            .c-body_container_inner_body_content_detail
              = "**** **** **** " + @default_card_information.last4
              %br
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year
            = form_tag(cards_path, method: :delete, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button.c-body_container_inner_body_content_btn 削除する
              = link_to "戻る", :back, class: "p-card_input_form_container_back"
= render partial: 'layouts/footer', locals: { footer: @footer }